fix gosec in golangci.yaml
kubernetes-sigs/kwok pull request #172
Opened 2022-12-19 11:07 UTC by wlp1153468871

Signed-off-by: wlp1153468871 <luping.wei@daocloud.io>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

part of #107

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-12-22 03:02 UTC, wzshiming requested changes
Revert the G110 and G304

2022-12-22 03:02 UTC, wzshiming commented on .golangci.yaml
> +    - gosec
Add follow config in `linters-settings`

```
  gosec:
    excludes:
      - G110
      - G304
    config:
      G301: "0750"
      G302: "0640"
      G306: "0640"
```

Revert the G110 and G304

2022-12-23 10:09 UTC, wzshiming commented on pkg/config/config.go
> +	file, err := os.Open(filepath.Clean(p))
`filepath.Clean` should be no longer needed

2022-12-23 10:10 UTC, wzshiming commented on pkg/kwokctl/runtime/cluster.go
> +	f, err := os.OpenFile(logs, os.O_RDONLY, 0600)
```suggestion
	f, err := os.OpenFile(logs, os.O_RDONLY, 0640)
```

The same goes for everything else

2022-12-23 10:10 UTC, wzshiming commented on pkg/utils/file/untar.go
> +			return copy(outFile, tr)
revert this

2022-12-28 07:32 UTC, wzshiming commented
/ok-to-test

2022-12-28 07:36 UTC, wzshiming commented
It looks like this change has caused some of the tests to fail, for the docker-compose implementation, docker and nerdctl

2022-12-28 07:38 UTC, wzshiming requested changes

2022-12-28 07:38 UTC, wzshiming commented on pkg/kwokctl/runtime/binary/cluster.go
> +	logs := filepath.Clean(c.GetLogPath(filepath.Base(name) + ".log"))
```suggestion
	logs := c.GetLogPath(filepath.Base(name) + ".log")
```

2022-12-28 07:38 UTC, wzshiming commented on pkg/kwokctl/runtime/cluster.go
> +	logs := filepath.Clean(c.GetLogPath(AuditLogName))
```suggestion
	logs := c.GetLogPath(AuditLogName)
```

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/exec/cmd.go
> +	cmdlinePath := filepath.Clean(path.Join(dir, "cmdline", filepath.Base(name)))
```suggestion
	cmdlinePath := path.Join(dir, "cmdline", filepath.Base(name))
```

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/exec/cmd.go
> +	pidPath := filepath.Clean(path.Join(dir, "pids", filepath.Base(name)+".pid"))
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/exec/cmd.go
> +	logFile, err := os.OpenFile(filepath.Clean(logPath), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0640)
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/exec/cmd.go
> +	pidPath := filepath.Clean(path.Join(dir, "pids", filepath.Base(name)+".pid"))
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/file/file.go
> +	file, err := os.OpenFile(filepath.Clean(name), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/file/file.go
> +	oldFile, err := os.OpenFile(filepath.Clean(oldpath), os.O_RDONLY, 0)
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/file/file.go
> +	newFile, err := os.OpenFile(filepath.Clean(newpath), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, fi.Mode())
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/file/untar.go
> +			outFile, err := os.OpenFile(filepath.Clean(name), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, fi.Mode())
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/file/untar.go
> +	r, err := os.Open(filepath.Clean(src))
ditto

2022-12-28 07:38 UTC, wzshiming commented on pkg/utils/file/untar.go
> +			outFile, err := os.OpenFile(filepath.Clean(name), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, fs.FileMode(hdr.Mode))
ditto

2023-01-03 10:01 UTC, wlp1153468871 commented on pkg/utils/file/untar.go
> +	r, err := os.Open(filepath.Clean(src))
I have solved it，thanks.

2023-01-03 11:02 UTC, wzshiming requested changes

2023-01-03 11:02 UTC, wzshiming commented on hack/verify-boilerplate.go
> +	b, err := os.ReadFile(filepath.Clean(filePath))
```suggestion
	b, err := os.ReadFile(filePath)
```

2023-01-03 11:02 UTC, wzshiming commented on pkg/cni/netns_linux.go
> +	mountPointFd, err := os.Create(filepath.Clean(nsPath))
```suggestion
	mountPointFd, err := os.Create(nsPath)
```

2023-01-05 07:00 UTC, wzshiming requested changes

2023-01-05 07:00 UTC, wzshiming commented on pkg/cni/netns_linux.go
> +	"path/filepath"
```suggestion
```

2023-01-05 07:55 UTC, wzshiming requested changes

2023-01-06 08:13 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +
Run `gofmt -w ./pkg/kwokctl/runtime/compose/cluster.go` to format this file

2023-01-06 08:40 UTC, wzshiming approved these changes
/approve
/lgtm

2023-01-06 08:55 UTC, merged