[kwokctl] Update start/stop for nerdctl
kubernetes-sigs/kwok pull request #249
Opened 2023-02-02 07:53 UTC by Zhuzhenghao

Signed-off-by: zhuzhenghao <zhenghao.zhu@daocloud.io>

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Update start/stop for nerdctl.

1. nerdctl supports `compose start` in [version 1.2.0](https://github.com/containerd/nerdctl/releases/tag/v1.2.0). Add judgement to  determine when not to use `compose start`.
2. same as `compost stop`

#### Which issue(s) this PR fixes:

Fixes #245

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2023-02-02 08:32 UTC, wzshiming requested changes

2023-02-02 08:32 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +var minNerdctlVersion = version.NewVersion(1, 2, 0)
```suggestion
// minNerdctlRestartSupportVersion is the start/stop feature added to nerdctl in 1.2
var minNerdctlRestartSupportVersion = version.NewVersion(1, 2, 0)
```

2023-02-02 08:32 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
>  	}
```suggestion
	// nerdctl does not support 'compose start' in v1.1.0 or earlier
	isOldNerdctl := false
	if conf.Options.Runtime == consts.RuntimeTypeNerdctl {
		nerdctlVersion, err = version.ParseFromBinary(context.Background(), consts.RuntimeTypeNerdctl)
		if err != nil {
			return err
		}
		if nerdctlVersion.LT(minNerdctlRestartSupportVersion) {
			isOldNerdctl = true
		}
	}
	
	subcommand := []string{"start"}
	if isOldNerdctl {
		subcommand = []string{"up", "-d"}
	}
```

2023-02-02 08:32 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +	if isRuntimeNerdctl && nerdctlVersion.LT(minNerdctlVersion) {
```suggestion
	if isOldNerdctl {
```

2023-02-02 09:23 UTC, wzshiming commented
https://github.com/kubernetes-sigs/kwok/blob/840110b20ab0b6b385d137c04eebf827c0ee2ff7/.github/workflows/test.yaml#L163

Bump it to 1.2 on ci

2023-02-02 10:13 UTC, Zhuzhenghao commented
> https://github.com/kubernetes-sigs/kwok/blob/840110b20ab0b6b385d137c04eebf827c0ee2ff7/.github/workflows/test.yaml#L163
> 
> Bump it to 1.2 on ci

Done.

2023-02-02 10:15 UTC, wzshiming commented
/ok-to-test

2023-02-02 10:42 UTC, wzshiming commented
https://github.com/kubernetes-sigs/kwok/actions/runs/4073407892/jobs/7017305293

Remove this `/etc/cni/tuning/allowlist.conf` file in ci

https://github.com/containernetworking/plugins/pull/826

2023-02-03 07:49 UTC, wzshiming requested changes

2023-02-03 07:49 UTC, wzshiming commented on .github/workflows/test.yaml
>            containerd-rootless-setuptool.sh install
```suggestion
          containerd-rootless-setuptool.sh install
          sudo chmod 0755 /etc/cni
```

2023-02-03 07:49 UTC, wzshiming commented on .github/workflows/test.yaml
> +          fi
```suggestion
```

2023-02-03 07:49 UTC, wzshiming commented on .github/workflows/test.yaml
> +  CGO_ENABLED: '0'
```suggestion
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  CGO_ENABLED: "0"
```

2023-02-03 13:07 UTC, wzshiming approved these changes
/approve
/lgtm

2023-02-03 13:08 UTC, merged