[WIP] Pass Verbosity to all components
kubernetes-sigs/kwok pull request #308
Opened 2023-02-21 01:51 UTC by Zhuzhenghao

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-03-06 04:35 UTC, Zhuzhenghao commented
/retest

2023-03-17 07:42 UTC, wzshiming commented
Can we have a test cover this change?

2023-03-21 03:07 UTC, Zhuzhenghao commented
Work on e2e test cases.

2023-03-21 03:57 UTC, Zhuzhenghao commented
/kind feature

2023-03-22 02:11 UTC, wzshiming requested changes

2023-03-22 02:11 UTC, wzshiming commented on pkg/log/wrapper.go
> +
```suggestion

func (l *Logger) Level() int {
	return l.level
}

```

2023-03-22 02:11 UTC, wzshiming commented on pkg/log/wrapper.go
> +func (l *Logger) ToKlogLevel() int {
```suggestion
func ToKlogLevel(level int) int {
```

2023-03-22 02:11 UTC, wzshiming commented on pkg/log/wrapper.go
> +func (l *Logger) ToLogSeverityLevel() string {
```suggestion
func ToLogSeverityLevel(level int) string {
```

2023-03-22 02:11 UTC, wzshiming commented on pkg/log/wrapper.go
> +func (l *Logger) ToKlogLevel() int {
move to new file

2023-03-22 02:11 UTC, wzshiming commented on pkg/log/wrapper.go
> +func (l *Logger) ToLogSeverityLevel() string {
move to new file

2023-03-22 02:11 UTC, wzshiming commented on pkg/log/wrapper.go
> +)
move to new file

2023-03-22 02:11 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
> +	Log
```suggestion
```

2023-03-22 02:11 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
> +
```suggestion
```

2023-03-22 02:11 UTC, wzshiming commented on pkg/kwokctl/cmd/create/cluster/cluster.go
> +	}
```suggestion
	flags.Options.Log = internalversion.Log{
		KlogLevel:     logger.ToKlogLevel(),
		SeverityLevel: logger.ToLogSeverityLevel(),
	}
```

Move to the installation phase

2023-03-27 06:57 UTC, wzshiming commented on pkg/kwokctl/components/etcd.go
> +	if conf.Version.GT(version.NewVersion(3, 3, 17)) && conf.LogLevel != log.InfoLevelSecurity {
This flag was added by 3.3.17? Shouldn't it be 3.4 or 3.3?

2023-04-06 02:30 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/kind.yaml.tpl
> +{{ if or .EtcdExtraArgs .EtcdExtraVolumes .Verbosity }}
Move to https://github.com/kubernetes-sigs/kwok/blob/730d50e32b7968c4377b285f97c67d4819e8b657/pkg/kwokctl/runtime/kind/kind.go#L47

2023-04-06 02:31 UTC, wzshiming commented on test/kwokctl/kwokctl_binary_verbosity.test.sh
> +# Copyright 2022 The Kubernetes Authors.
```suggestion
# Copyright 2023 The Kubernetes Authors.
```

2023-04-06 02:31 UTC, wzshiming commented on test/kwokctl/kwokctl_docker_verbosity.test.sh
> +# Copyright 2022 The Kubernetes Authors.
```suggestion
# Copyright 2023 The Kubernetes Authors.
```

2023-04-06 10:21 UTC, wzshiming commented on pkg/kwokctl/components/etcd.go
> +		etcdArgs = append(etcdArgs, "--log-level="+conf.LogLevel)
https://etcd.io/docs/v3.5/upgrades/upgrade_3_4/#deprecating-etcd---debug-flag-now---log-leveldebug

If etcd is less than 3.4 and the logs level is debug, then we use `--debug`

2023-04-07 15:41 UTC, wzshiming commented
```
error validating "pkg/log/convert.go": the file is missing a boilerplate
```

2023-04-07 16:29 UTC, Zhuzhenghao commented
/retest

2023-04-07 17:19 UTC, wzshiming approved these changes
/approve
/lgtm

2023-04-07 20:27 UTC, merged