support extra args
kubernetes-sigs/kwok pull request #311
Opened 2023-02-22 01:58 UTC by KunWuLuan

#### What type of PR is this?
/kind feature
/kind api-change

#### What this PR does / why we need it:
With this commit, we can specify some extra arguments in config file like:
```
kind: KwokctlConfiguration
apiVersion: kwok.x-k8s.io/v1alpha1
componentsPatches:
  - name: kube-apiserver
    extraArgs:
      - key: kubelet-timeout
        value: 555s
```
Then we can pass these arguments to the commands of components.
```
 $ kwok git:(support-extra-args) ✗ docker inspect f1dfaf7228c5 
[
    {
        "Id": "xxx",
        "Created": "2023-02-22T01:39:28.703077028Z",
        "Path": "kube-apiserver",
        "Args": [
            "--admission-control=",
            "--etcd-servers=http://kwok-kwok-etcd:2379",
            "--etcd-prefix=/registry",
            "--allow-privileged=true",
            "--kubelet-timeout=555s",
            "--bind-address=0.0.0.0",
            "--secure-port=6443",
            "--tls-cert-file=/etc/kubernetes/pki/admin.crt",
            "--tls-private-key-file=/etc/kubernetes/pki/admin.key",
            "--client-ca-file=/etc/kubernetes/pki/ca.crt",
            "--service-account-key-file=/etc/kubernetes/pki/admin.key",
            "--service-account-signing-key-file=/etc/kubernetes/pki/admin.key",
            "--service-account-issuer=https://kubernetes.default.svc.cluster.local"
...
            "Cmd": [
                "--admission-control=",
                "--etcd-servers=http://kwok-kwok-etcd:2379",
                "--etcd-prefix=/registry",
                "--allow-privileged=true",
                "--kubelet-timeout=555s",
                "--bind-address=0.0.0.0",
                "--secure-port=6443",
                "--tls-cert-file=/etc/kubernetes/pki/admin.crt",
                "--tls-private-key-file=/etc/kubernetes/pki/admin.key",
                "--client-ca-file=/etc/kubernetes/pki/ca.crt",
                "--service-account-key-file=/etc/kubernetes/pki/admin.key",
                "--service-account-signing-key-file=/etc/kubernetes/pki/admin.key",
                "--service-account-issuer=https://kubernetes.default.svc.cluster.local"
            ],
...
```
#### Which issue(s) this PR fixes:
to #307

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-02-22 02:09 UTC, wzshiming commented
/ok-to-test

2023-02-22 03:47 UTC, KunWuLuan commented
/test

2023-02-22 03:48 UTC, KunWuLuan commented
/test all

2023-02-22 05:15 UTC, wzshiming requested changes
This feature also requires support for the Kind runtime

2023-02-22 05:15 UTC, wzshiming commented on pkg/apis/internalversion/kwokctl_configuration_types.go
> +type KwokctlConfigurationComponentsPatches struct {
```suggestion
type ComponentsPatches struct {
```

2023-02-22 05:15 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
> +	Components []Component
```suggestion
	Components []Component `json:"components,omitempty"`
```

2023-02-22 05:15 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
> +	ComponentsPatches []KwokctlConfigurationComponentsPatches
```suggestion
	ComponentsPatches []KwokctlConfigurationComponentsPatches `json:"componentsPatches,omitempty"`
```

2023-02-22 05:15 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
> +type ExtraArgs struct {
ditto

2023-02-22 05:15 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
> +type KwokctlConfigurationComponentsPatches struct {
ditto

2023-02-22 05:15 UTC, wzshiming commented on pkg/kwokctl/runtime/util.go
> +Copyright 2022 The Kubernetes Authors.
```suggestion
Copyright 2023 The Kubernetes Authors.
```

2023-02-22 05:15 UTC, wzshiming commented on pkg/kwokctl/runtime/util.go
> +}
```suggestion
// GetComponentExtraArgs returns the extra args for a components patches.
func GetComponentExtraArgs(conf *internalversion.KwokctlConfiguration, componentName string) []string {
	componentPatches, ok := slices.Find(conf.ComponentsPatches, func(patch internalversion.KwokctlConfigurationComponentsPatches) bool {
		return patch.ComponentName == componentName
	})
	if !ok {
		return []string{}
	}

	args := slices.Map(componentPatches.ExtraArgs, func(arg internalversion.ExtraArgs) string {
		return fmt.Sprintf("--%s=%s", arg.Key, arg.Value)
	})
	return args
}
```

2023-02-22 05:23 UTC, wzshiming commented on pkg/kwokctl/runtime/binary/cluster.go
> +			ExtraArgs:         runtime.GetComponentExtraArgs(config, "kube-contoller-manager"),
```suggestion
			ExtraArgs:         runtime.GetComponentExtraArgs(config, "kube-controller-manager"),
```

2023-02-23 03:06 UTC, KunWuLuan commented on pkg/kwokctl/runtime/binary/cluster.go
> +			ExtraArgs:         runtime.GetComponentExtraArgs(config, "kube-contoller-manager"),
done, thanks!

2023-02-23 03:14 UTC, KunWuLuan commented
```
➜  kwok git:(support-extra-args) ✗ ./bin/darwin/amd64/kwokctl create cluster --v=-5 --runtime=kind --kind-binary=/.../kind-darwin-amd64 --config /.../kwok.yaml
DEBUG Load config                                                                                                                                  path=["/Users/yueming/.kwok/kwok.yaml"]
Creating cluster                                                                                                                                                              cluster=kwok
2023/02/23 09:34:12 kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      # enable auditing flags on the API server
      extraArgs:
        kubelet-timeout: 555s
  # mount the local file on the control plane
  extraMounts:
  - hostPath: /Users/yueming/.kwok/clusters/kwok/kwok.yaml
    containerPath: /etc/kwok/kwok.yaml
    readOnly: true
```
```
➜  kwok git:(support-extra-args) ✗ kk get po kube-apiserver-kwok-kwok-control-plane -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.128.2:6443
    kubernetes.io/config.hash: 414bc58e3301687a9fadbb40036807f6
    kubernetes.io/config.mirror: 414bc58e3301687a9fadbb40036807f6
    kubernetes.io/config.seen: "2023-02-23T01:34:37.488079885Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2023-02-23T01:34:37Z"
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver-kwok-kwok-control-plane
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: kwok-kwok-control-plane
    uid: 25c692f3-b5f3-443e-b94e-7ab2ab86e725
  resourceVersion: "298"
  uid: c29fad3d-cb8a-444d-a293-a10892fabd72
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.128.2
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-timeout=555s
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --runtime-config=
    - --secure-port=6443
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/16
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
```

2023-02-23 08:47 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/cluster.go
> +	getKindRuntimeExtraArgs := func(s string) []internalversion.ExtraArgs {
Don't convert back and forth here

``` golang
slices.Find(conf.ComponentsPatches, func(patch internalversion.ComponentsPatches) bool {
		return patch.ComponentName == s
	})
```

2023-02-23 08:47 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/cluster.go
> +		SchedulerExtraArgs: getKindRuntimeExtraArgs("kube-scheduler"),
Looks like kube-controller-manager is missing.

2023-02-24 13:42 UTC, wzshiming requested changes
Can we have a test to cover this change to avoid being broken in future.

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/prometheus_deployment.go
> +	PrometheusExtraArgs []string
```suggestion
	ExtraArgs []string
```

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/prometheus_deployment.yaml.tpl
> +        {{ range .PrometheusExtraArgs }}
```suggestion
        {{ range .ExtraArgs }}
```

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/kwok_controller_pod.go
> +	KwokControllerExtraArgs []string
```suggestion
	ExtraArgs []string
```

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/kwok_controller_pod.yaml.tpl
> +    {{ range .KwokControllerExtraArgs }}
```suggestion
    {{ range .ExtraArgs }}
```

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/kind.go
> +	APIServerExtraArgs         []internalversion.ExtraArgs
```suggestion
	EtcdExtraArgs             []internalversion.ExtraArgs
	ApierverExtraArgs         []internalversion.ExtraArgs
```

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/kind.go
>  	_ "embed"
Move to bottom

2023-02-24 13:42 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/cluster.go
> +	getKindRuntimeExtraArgs := func(s string) []internalversion.ExtraArgs {
Move to outside of the function

2023-02-24 13:42 UTC, wzshiming commented on pkg/apis/v1alpha1/kwokctl_configuration_types.go
>  }
```suggestion
	// ComponentsPatches holds information about the components patches.
	ComponentsPatches []ComponentPatches `json:"componentsPatches,omitempty"`
}

// ExtraArgs holds information about the extra args.
type ExtraArgs struct {
	// Key is the key of the extra args.
	Key string `json:"key"`
	// Value is the value of the extra args.
	Value string `json:"value"`
}

// ComponentPatches holds information about the component patches.
type ComponentPatches struct {
	// Name is the name of the component.
	Name string `json:"name"`
	// ExtraArgs is the extra args to be patched on the component.
	ExtraArgs []ExtraArgs `json:"extraArgs,omitempty"`
}
```

2023-02-24 13:42 UTC, wzshiming commented on pkg/apis/internalversion/kwokctl_configuration_types.go
>  }
```suggestion
	// ComponentsPatches holds information about the components patches.
	ComponentsPatches []ComponentPatches
}

// ExtraArgs holds information about the extra args.
type ExtraArgs struct {
	// Key is the key of the extra args.
	Key string
	// Value is the value of the extra args.
	Value string
}

// ComponentPatches holds information about the component patches.
type ComponentPatches struct {
	// Name is the name of the component.
	Name string
	// ExtraArgs is the extra args to be patched on the component.
	ExtraArgs []ExtraArgs
}
```

2023-02-24 13:46 UTC, wzshiming commented
BTY, CI didn't pass we should let it passed.

2023-03-23 09:01 UTC, KunWuLuan commented
Sorry, I had some urgent requirements to develop in the past two weeks. I updated the code today and now it passes the CI tests successfully.

2023-03-23 09:14 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/prometheus_deployment.go
> +
```suggestion
```

2023-03-23 09:14 UTC, wzshiming commented on pkg/kwokctl/runtime/kind/kind.go
> +
```suggestion
```

2023-03-23 11:44 UTC, wzshiming commented on test/kwokctl/kwokctl_authorization_test.sh
> +  KWOK_KUBE_VERSION="${release}" kwokctl -v=-4 --config "${DIR}/fake-kwok-config.yaml" create cluster --name "${name}" --timeout 10m --wait 10m --quiet-pull --kube-authorization
revert

2023-03-23 11:44 UTC, wzshiming commented on test/kwokctl/kwokctl_auto_detect.test.sh
> +    KWOK_KUBE_VERSION="${release}" kwokctl -v=-4 --config "${DIR}/fake-kwok-config.yaml"  create cluster --timeout 10m --wait 10m --quiet-pull --config "${DIR}"/kwokctl-config-runtimes.yaml || exit 1
revert

2023-03-23 11:44 UTC, wzshiming commented on test/kwokctl/kwokctl_benchmark_test.sh
> +  KWOK_KUBE_VERSION="${KWOK_KUBE_VERSION}" kwokctl -v=-4 --config "${DIR}/fake-kwok-config.yaml" create cluster --timeout 10m --wait 10m --quiet-pull || {
revert

2023-03-23 11:44 UTC, wzshiming commented on test/kwokctl/kwokctl_multi_cluster_test.sh
> +  KWOK_KUBE_VERSION="${release}" kwokctl --config "${DIR}/fake-kwok-config.yaml" -v=-4 create cluster --name "${name}" --timeout 10m --wait 10m --quiet-pull
revert

2023-03-23 11:44 UTC, wzshiming commented on test/kwokctl/fake-kwok-config.yaml
> +kind: KwokctlConfiguration
All use log flag?

2023-03-23 12:48 UTC, KunWuLuan commented
/test

2023-03-23 13:00 UTC, KunWuLuan commented
/test all

2023-03-23 13:07 UTC, wzshiming commented on test/kwokctl/fake-kwok-config.yaml
> +        value: "10"
```suggestion
        value: "-4"
```

2023-03-23 13:08 UTC, wzshiming commented on test/kwokctl/fake-kwok-config.yaml
> +        value: "info"
```suggestion
        value: "debug"
```

2023-03-23 13:08 UTC, wzshiming commented on test/kwokctl/fake-kwok-config.yaml
> +        value: "info"
```suggestion
        value: "debug"
```

2023-03-25 10:20 UTC, wzshiming reviewed
Squash the commits, others lgtm.

2023-03-25 10:20 UTC, wzshiming commented on test/kwokctl/kwokctl_workable_test.sh
> +    KWOK_KUBE_VERSION="${release}" kwokctl --config "${DIR}/fake-kwok-config-1.yaml" -v=-4 create cluster --name "${name}" --timeout 10m --wait 10m --quiet-pull --prometheus-port 9090 --controller-po
```suggestion
    KWOK_KUBE_VERSION="${release}" kwokctl --config "${DIR}/fake-kwok-config-le-1-17.yaml" -v=-4 create cluster --name "${name}" --timeout 10m --wait 10m --quiet-pull --prometheus-port 9090 --controller-port 10247 --etcd-port=2400 --kube-scheduler-port=10250 --kube-controller-manager-port=10260
```

2023-03-26 05:41 UTC, wzshiming commented
/approve
/lgtm

Thank you for your contribution!

2023-03-26 05:41 UTC, merged