initialize nodeSelectorFunc when --manage-nodes-with-label-selector is set
kubernetes-sigs/kwok pull request #347
Opened 2023-03-04 05:10 UTC by lzlaa

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The reason why #346 happened is that kwok doesn't initializes `nodeSelectorFunc` when `--manage-nodes-with-label-selector` is set, this PR will initialize `nodeSelectorFunc` to fix it.

#### Which issue(s) this PR fixes:

Fixes #346 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-03-04 07:24 UTC, wzshiming requested changes

2023-03-04 07:24 UTC, wzshiming commented on pkg/kwok/controllers/controller.go
> -		// client-go supports label filtering, so ignore this.
As this comment says we don't need to use this function to filter node we should check for nil before calling this function😄

2023-03-04 08:53 UTC, wzshiming commented
it's okay, squash commits. and can we have a test cover this change?

2023-03-04 08:56 UTC, wzshiming commented
/ok-to-test

2023-03-04 15:02 UTC, lzlaa commented
> it's okay, squash commits. and can we have a test cover this change?

Thanks for your work, I add an unit  test to cover this change.

2023-03-05 08:34 UTC, wzshiming commented on pkg/kwok/controllers/controller_test.go
> +Copyright 2022 The Kubernetes Authors.
```suggestion
Copyright 2023 The Kubernetes Authors.
```

2023-03-05 13:54 UTC, lzlaa commented
I have resolved your comment. @wzshiming

2023-03-06 01:43 UTC, wzshiming commented
/approve
/lgtm

Thank you for your contribution

2023-03-06 01:44 UTC, merged