fix(kind cleanup): fix task SC2015
kubernetes-sigs/kwok pull request #521
Opened 2023-04-19 06:24 UTC by liu-xg

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

cleanup code

#### Which issue(s) this PR fixes:
xref #470 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
none

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

2023-04-19 06:46 UTC, wzshiming commented on hack/e2e-test.sh
> +        fi
```suggestion
        [[ "${arg#*=}" != "${arg}" ]] && SKIPS+=("${arg#*=}") || { SKIPS+=("${2}") && shift; } || :
```

2023-04-19 06:47 UTC, wzshiming commented on hack/e2e-test.sh
> +        fi
Add the suffix ` || :` for all

2023-04-19 06:54 UTC, liu-xg commented on hack/e2e-test.sh
> +        fi
ok

2023-04-19 09:32 UTC, wzshiming commented
/ok-to-test

2023-04-19 09:33 UTC, wzshiming commented
Do not merge main branches, please rebase and squash

2023-04-20 01:32 UTC, wzshiming requested changes
Turn off the SC2015 in the script, then rebase and squash

2023-04-20 01:55 UTC, wzshiming commented on hack/verify-shellcheck.sh
> +  #2015
```suggestion
```

2023-04-20 02:08 UTC, liu-xg commented on hack/verify-shellcheck.sh
> +  #2015
ok

2023-04-20 03:44 UTC, wzshiming approved these changes
/approve
/lgtm

2023-04-20 04:13 UTC, merged