make build support macos m1
kubernetes-sigs/kwok pull request #69
Opened 2022-11-17 16:55 UTC by carlory

Signed-off-by: carlory <baofa.fan@daocloud.io>

2022-11-17 16:57 UTC, carlory commented
/kind feature

2022-11-18 02:27 UTC, wzshiming requested changes
I don't think it's reliable to get information about the current machine from 'go env', which can be modified by environment variables.

maybe like below:
``` patch
diff --git a/Makefile b/Makefile
index 3229ee2..337d29f 100644
--- a/Makefile
+++ b/Makefile
@@ -50,6 +50,8 @@ KWOK_IMAGE ?= $(STAGING_IMAGE_PREFIX)/kwok
 
 CLUSTER_IMAGE ?= $(STAGING_IMAGE_PREFIX)/cluster
 
+PLATFORM ?= $(shell ./hack/get-platform.sh)
+
 IMAGE_PLATFORMS ?= linux/amd64 linux/arm64
 
 BINARY_PLATFORMS ?= linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64
@@ -78,6 +80,7 @@ build: vendor
 	@./hack/releases.sh \
 		$(addprefix --bin=, $(BINARY)) \
 		$(addprefix --extra-tag=, $(EXTRA_TAGS)) \
+		--platform=${PLATFROM} \
 		--bucket=${BUCKET} \
 		--gh-release=${GH_RELEASE} \
 		--image-prefix=${IMAGE_PREFIX} \
@@ -112,6 +115,7 @@ cross-build: vendor
 image:
 	@./images/kwok/build.sh \
 		$(addprefix --extra-tag=, $(EXTRA_TAGS)) \
+		--platform=${PLATFROM} \
 		--image=${KWOK_IMAGE} \
 		--version=${VERSION} \
 		--staging-prefix=${STAGING_PREFIX} \

```

./hack/get-platform.sh
``` bash
# get architecture of the machine
function arch() {
  local arch
  arch="$(uname -m)"

  case "${arch}" in
  x86_64 | amd64 | x64)
    echo "amd64"
    ;;
  i386 | i486 | i586 | i686 | x86)
    echo "386"
    ;;
  armv8* | aarch64* | arm64)
    echo "arm64"
    ;;
  armv7* | armhf)
    echo "arm"
    ;;
  *)
    echo "${arch}"
    ;;
  esac
}

# get os of the system
function os() {
  local os
  os="$(uname -s)"

  echo "${os,,}"
}

echo "$(os)/$(arch)"
```

2022-11-18 02:37 UTC, wzshiming commented
/ok-to-test

2022-11-18 02:47 UTC, wzshiming commented
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kwok/69/pull-kwok-verify-main/1593433252901687296

```
[*] Verifying ends newline...
Add a new line in ends for below files
./hack/get-platform.sh
```

and should also need `chmod +x ./hack/get-platform.sh`

2022-11-18 02:55 UTC, carlory commented
@wzshiming updated

2022-11-18 03:35 UTC, wzshiming commented
/lgtm
/approve

2022-11-18 04:58 UTC, merged