add issue template
kubernetes-sigs/kwok pull request #76
Opened 2022-11-20 15:57 UTC by carlory

2022-11-21 02:45 UTC, carlory commented
cc @wzshiming

2022-11-22 01:58 UTC, wzshiming commented
/ok-to-test

2022-11-22 05:45 UTC, carlory commented
cc @wzshiming

2022-11-22 07:20 UTC, wzshiming requested changes
Add a configuration file for the Support Request

.github/ISSUE_TEMPLATE/config.yml
```
contact_links:
  - name: Support Request
    url: https://github.com/kubernetes-sigs/kwok/discussions
    about: Support request or question relating to Kwok
```

2022-11-22 07:20 UTC, wzshiming commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +        </details>
```suggestion
    id: osVersion
    attributes:
      label: OS version
      value: |
        <details>
        ```console        
        # On Linux:
        $ cat /etc/os-release
        # paste output here
        $ uname -a
        # paste output here

        # On Darwin:
        $ uname -a
        # paste output here

        # On Windows:
        C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
        # paste output here
        ```
        </details>
```

2022-11-22 07:29 UTC, carlory commented
@wzshiming updated!

2022-11-22 08:12 UTC, wzshiming reviewed
Maybe should add [PULL_REQUEST_TEMPLATE.md](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as well

2022-11-22 08:12 UTC, wzshiming commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +body:
```suggestion
body:
  - type: checkboxes
    id: usage
    attributes:
      label: How to use it?
      options:
        - label: kwok
        - label: kwokctl --runtime=docker (default runtime)
        - label: kwokctl --runtime=binary
        - label: kwokctl --runtime=nerdctl
        - label: kwokctl --runtime=kind

```

2022-11-22 08:12 UTC, wzshiming commented on .github/ISSUE_TEMPLATE/bug-report.yaml
> +        </details>
```suggestion
```

2022-11-22 08:21 UTC, carlory commented
/rettile add issue and pr template

2022-11-22 08:26 UTC, carlory commented
@wzshiming updated!

2022-11-23 05:52 UTC, wzshiming commented
```
[*] Verifying ends newline...
Add a new line in ends for below files
./.github/ISSUE_TEMPLATE/enhancement.yaml
./.github/ISSUE_TEMPLATE/failing-test.yaml
```

2022-11-23 05:55 UTC, carlory commented
@wzshiming updated

2022-11-23 09:24 UTC, carlory commented
/test pull-kwok-e2e-test-mai

2022-11-23 15:13 UTC, carlory commented
/test pull-kwok-e2e-test-main

2022-11-24 10:39 UTC, wzshiming commented
/approve
/lgtm

2022-11-24 10:44 UTC, merged