add docker-compose online download
kubernetes-sigs/kwok pull request #93
Opened 2022-11-28 05:40 UTC by fengshunli

2022-11-28 05:46 UTC, wzshiming requested changes

2022-11-28 05:46 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +
```suggestion
```

2022-11-28 05:46 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +}
```suggestion
var archAliasMapping = map[string]string{
	"arm64": "aarch64",
}

func archAlias(arch string) string {
	if v, ok := archAliasMapping[arch]; ok {
		return v
	}
	return arch
}
```

2022-11-28 05:46 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +}
Please add alias for amd, 386 arm, etc

2022-11-28 05:46 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +		cmd := exec.Command(conf.Runtime, "compose")
Uniform change to exec.Command wrap `utils.Exec`

2022-11-28 05:46 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +			dockerComposePath := utils.PathJoin(conf.Workdir, "bin", "docker-compose")
```suggestion
			dockerComposePath := utils.PathJoin(conf.Workdir, "bin", "docker-compose"+vars.BinSuffix)
```

2022-11-28 06:23 UTC, wzshiming commented
Don't open a PR every time and `git push -f` directly onto the original branch

2022-11-28 06:27 UTC, fengshunli commented
> git push -f
ok

2022-11-28 06:44 UTC, wzshiming requested changes
Delete the download docker-compose logic from CI for test the patch is working

2022-11-28 06:44 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> -
Keep a blank line

2022-11-28 06:44 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +	"x86_64": "x86_64",
```suggestion
	"arm64": "aarch64",
	"arm: "armv7",
	"amd64": "x86_64",
	"386": "x86",
```

2022-11-28 06:44 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +		return archMapping[arch]
```suggestion
	if v, ok := archMapping[arch]; ok {
		return v
```

2022-11-28 06:44 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +	DockerComposeVersion = addPrefixV(getEnv("KWOK_DOCKER_COMPOSE_VERSION", "v2.13.0"))
```suggestion
	// DockerComposeVersion is the version of docker-compose to use.
	DockerComposeVersion = addPrefixV(getEnv("KWOK_DOCKER_COMPOSE_VERSION", "v2.13.0"))
```

2022-11-28 06:44 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +
```suggestion
```

2022-11-28 06:45 UTC, wzshiming commented
/ok-to-test

2022-11-28 06:45 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +	composePath, err := c.getCompose(ctx, args...)
```suggestion
	commands, err := c.getCompose(ctx, args...)
```

2022-11-28 06:45 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +	composePath, err := c.getCompose(ctx, args...)
```suggestion
	commands, err := c.getCompose(ctx, args...)
```

2022-11-28 06:46 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +func (c *Cluster) getCompose(ctx context.Context, args ...string) ([]string, error) {
```suggestion
func (c *Cluster) buildComamnds(ctx context.Context, args ...string) ([]string, error) {
```

2022-11-28 06:50 UTC, wzshiming commented
/retitle Download Docker-Compose-v2 automatically if necessary

2022-11-28 06:56 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +
```suggestion
	# DockerComposeBinaryPrefix is the binary of docker-compose.
	DockerComposeBinaryPrefix = "https://github.com/docker/compose/releases/download/" + DockerComposeVersion 
	
	MustDockerComposeBinary = DockerComposeBinaryPrefix + "/docker-compose-" + runtime.GOOS + "-" + archAlias(runtime.GOARCH) + BinSuffix

```

2022-11-28 07:12 UTC, wzshiming requested changes

2022-11-28 07:12 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +		c.Logger().Printf("Download Compose failed: %v", err)
```suggestion
		c.Logger().Printf("Failed to build commands: %v", err)
```

2022-11-28 07:12 UTC, wzshiming commented on pkg/kwokctl/runtime/compose/cluster.go
> +		c.Logger().Printf("Download Compose failed: %v", err)
```suggestion
		c.Logger().Printf("Failed to build commands: %v", err)
```

2022-11-28 07:17 UTC, wzshiming commented on pkg/kwokctl/vars/vars.go
> +	MustDockerComposeBinary = DockerComposeBinaryPrefix + "/docker-compose" + "-" + runtime.GOOS + "-" + archAlias(runtime.GOARCH) + BinSuffix
Follow other variables, allow args in `kwokctl create cluster` to modify it

2022-11-28 10:26 UTC, wzshiming commented
> Delete the download docker-compose logic from CI for test the patch is working

2022-11-28 10:30 UTC, wzshiming requested changes

2022-11-28 10:31 UTC, wzshiming commented
> Delete the download docker-compose logic from CI for test the patch is working
You missed that comment

2022-11-30 06:27 UTC, wzshiming commented
Fixed by #104
/close

2022-11-30 06:27 UTC, closed without merging